name: Release Creation

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            # Substitute the Manifest and Download URLs in the module.json
            # for a FULL RELEASE
            - name: Substitute Manifest and Download Links For Versioned Ones
              if: "!github.event.release.prerelease"
              id: sub_release_manifest_version
              uses: microsoft/variable-substitution@v1
              with:
                  files: "system.json"
              env:
                  version: ${{github.event.release.tag_name}}
                  url: https://github.com/${{github.repository}}
                  manifest: https://github.com/${{github.repository}}/releases/latest/download/system.json
                  download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.zip

            # Substitute the Manifest and Download URLs in the module.json
            # for a PRE RELEASE. Manifest pointing to live module.json on branch,
            # which is updated after tag.
            - name: Substitute Manifest and Download Links For Versioned Ones
              if: "github.event.release.prerelease"
              id: sub_prerelease_manifest_version
              uses: microsoft/variable-substitution@v1
              with:
                  files: "system.json"
              env:
                  version: ${{github.event.release.tag_name}}
                  url: https://github.com/${{github.repository}}
                  manifest: https://raw.githubusercontent.com/${{github.repository}}/main/system.json
                  download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.zip

            - run: zip -r ./system.zip system.json assets/ dist/ lang/ styles/ templates/ packs/ template.json changelog.md LICENSE 

            # Create a release for this specific version
            - name: Update Release with Files
              if: "!github.event.release.prerelease"
              id: create_version_release
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true # Set this to false if you want to prevent updating existing releases
                  name: ${{ github.event.release.name }}
                  draft: false
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: "./system.json, ./system.zip"
                  tag: ${{ github.event.release.tag_name }}
                  body: ${{ github.event.release.body }}

            #  OR create a pre-release for this specific version
            - name: Update Release with Files
              if: "github.event.release.prerelease"
              id: create_version_prerelease
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true # Set this to false if you want to prevent updating existing releases
                  name: ${{ github.event.release.name }}
                  draft: false
                  prerelease: true
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: "./system.json, ./system.zip"
                  tag: ${{ github.event.release.tag_name }}
                  body: ${{ github.event.release.body }}
